## Imports

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

import numpy as np
import pandas as pd
import cv2
import os

## Load the dataset

In [23]:
action_space = ['walking', 'running', 'jogging', 'boxing', 'handwaving', 'handclapping']

root_folder = ".\\dataset\\"
not_gray_list = []

for action in action_space:
    total_frames = 0
    not_gray = 0
    folder = os.path.join(root_folder, action)
    print(action)
    file_num = 0
    for filename in os.listdir(folder):
        size = len(os.listdir(folder))
        file_num += 1
        print(f"{file_num:03}/{size:03}", end="\r")
        file_path = os.path.join(folder, filename)
        if os.path.isfile(file_path):
            cap = cv2.VideoCapture(file_path)
            frames = []
            while True:
                ret, frame = cap.read()
                if not ret:
                    break
                frame = np.array(frame)
                for x in frame:
                    for y in x:
                        if not y[0] == y[1] and y[0]==y[2]: 
                            not_gray_list.append(y)
                            not_gray += 1

                        total_frames += 1
                
                #frames.append(frame)
            cap.release()
            if 'files_dict' not in locals():
                files_dict = {}
            test = np.array(frames)
            #files_dict[filename] = np.array(frames)
            #print(test.shape)
            #print(test)
            
    print(f"{action}:\t{not_gray}/{total_frames} frames are not grayscaled ({not_gray/total_frames:.2%})")

    






walking
walking:	6/1263264000 frames are not grayscaled (0.00%)
running
running:	0/739296000 frames are not grayscaled (0.00%)
jogging
jogging:	1/842572800 frames are not grayscaled (0.00%)
boxing
boxing:	67/867590400 frames are not grayscaled (0.00%)
handwaving
handwaving:	881/1030617600 frames are not grayscaled (0.00%)
handclapping
handclapping:	41/819206400 frames are not grayscaled (0.00%)


[0 2 0]
[0 2 0]
[0 1 0]
[0 2 0]
[0 2 0]
[0 2 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 2 0]
[0 1 0]
[0 1 0]
[0 2 0]
[0 2 0]
[0 2 0]
[0 2 0]
[0 2 0]
[0 2 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 2 0]
[0 1 0]
[0 2 0]
[0 2 0]
[0 1 0]
[0 2 0]
[0 2 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 2 0]
[0 2 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 2 0]
[0 1 0]
[0 1 0]
[0 2 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 2 0]
[0 1 0]
[0 2 0]
[0 2 0]
[0 2 0]
[0 2 0]
[0 2 0]
[0 2 0]
[0 2 0]
[0 2 0]
[0 2 0]
[0 2 0]
[0 1 0]
[0 1 0]
[0 2 0]
[0 1 0]
[0 2 0]
[0 1 0]
[0 1 0]
[0 2 0]
[0 2 0]
[0 1 0]
[0 1 0]
[0 2 0]
[0 2 0]
[0 2 0]
[0 2 0]
[0 2 0]
[0 1 0]
[0 1 0]
[0 2 0]
[0 1 0]
[0 2 0]
[0 2 0]
[0 2 0]
[0 1 0]
[0 2 0]
[0 2 0]
[0 2 0]
[0 2 0]
[0 2 0]
[0 2 0]
[0 2 0]
[0 2 0]
[0 1 0]
[0 2 0]
[0 2 0]
[0 2 0]
[0 1 0]
[0 2 0]
[0 2 0]
[0 2 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 2 0]
[0 1 0]
[0 2 0]
[0 2 0]
[0 2 0]
[0 1 0]
[0 1 0]
[0 2 0]
[0 1 0]
[0 1 0]
[0 2 0]
[0 2 0]
[0 2 0]
[0 1 0]
[0 2 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 2 0]
[0 2 0]
[0 1 0]
[0 2 0]
[0 1 0]
[0 2 0]
